services:
  web:
    restart: "no"
  db:
    restart: "no"
    volumes:
      # mount host volume
      # - ./db_data_dev:/var/lib/mysql
    # mount container volume
      - db_data_dev:/var/lib/mysql
  phpmyadmin:
    restart: "no"